CREATE DATABASE hello123;
use hello123;

CREATE TABLE SUPPLIERS1
(
SUPPLIER_NUMBER VARCHAR(255) PRIMARY KEY,
SUPPLIER_NAME VARCHAR(255),
STATUS INT,
CITY VARCHAR(255)
);
INSERT INTO SUPPLIERS1(SUPPLIER_NUMBER, SUPPLIER_NAME,STATUS,CITY )
VALUES
('S1','SARALA',20,'BOMBAY'),
('S2','UMA',10,'CHENNAI'),
('S3','NEHRU',30,'CHENNAI'),
('S4','PRIYA',20,'BOMBAY'),
('S5','ANAND',30,'DELHI');

SELECT * FROM SUPPLIERS1;

CREATE TABLE  PARTS1
(
PART_NUMBER VARCHAR(255) PRIMARY KEY,
PROJECT_NAME VARCHAR(255),
COLOR VARCHAR(255),
WEIGHT FLOAT,
CITY VARCHAR(255)
);
INSERT INTO PARTS1(PART_NUMBER,PROJECT_NAME,COLOR,WEIGHT,CITY )
VALUES
('P1','NUT','RED',12.0,'BOMBAY'),
('P2','BOLT','GREEN',17.0,'CHENNAI'),
('P3','SCREW','BLUE',17.0,'BANGLORE'),
('P4','SCREW','RED',14.0,'BOMBAY'),
('P5','CAM','BLUE',12.0,'CHENNAI'),
('P6','COG','RED',19.0,'BOMBAY');


SELECT * FROM PARTS1;

CREATE TABLE PROJECTS1
(
PROJECT_NUMBER VARCHAR(255) PRIMARY KEY,
PROJECT_NAME VARCHAR(255),
CITY VARCHAR(255)
);
INSERT INTO PROJECTS1(PROJECT_NUMBER,PROJECT_NAME,CITY )
VALUES
('J1','SORTER','CHENNAI'),
('J2','DISPLAY','NELLAI'),
('J3','OCR','DELHI'),
('J4','CONSOLE','DELHI'),
('J5','RAID','BOMBAY'),
('J6','EDS','BANGLORE'),
('J7','TAPE','BOMBAY');
SELECT * FROM PROJECTS1;

CREATE TABLE SHIPMENTS1
(
SUPPLIER_NUMBER VARCHAR(255),
PART_NUMBER VARCHAR(255),
PROJECT_NUMBER VARCHAR(255),
QUANTITY INT
);
INSERT INTO SHIPMENTS1(SUPPLIER_NUMBER,PART_NUMBER,PROJECT_NUMBER,QUANTITY )
VALUES
('S1','P1','J1',200),
('S1','P1','J4',700),
('S2','P3','J1',400),
('S2','P3','J2',200),
('S2','P3','J3',200),
('S2','P3','J4',500),
('S2','P3','J5',600),
('S2','P3','J6',400),
('S2','P3','J7',800),
('S2','P5','J2',100),
('S3','P3','J1',200),
('S3','P4','J2',500),
('S4','P6','J3',300),
('S4','P6','J7',300),
('S5','P2','J2',200),
('S5','P2','J4',100),
('S5','P5','J5',500),
('S5','P5','J7',100),
('S5','P6','J2',200),
('S5','P1','J4',100),
('S5','P3','J4',200),
('S5','P4','J4',800),
('S5','P5','J4',400),
('S5','P6','J4',500);

SELECT * FROM SHIPMENTS1;

--1 assignment_1
SELECT * FROM PROJECTS1;

--2
SELECT * FROM PROJECTS1 WHERE CITY = 'BOMBAY';

--3
SELECT DISTINCT SUPPLIERS1.SUPPLIER_NAME FROM SUPPLIERS1
JOIN SHIPMENTS1 ON SHIPMENTS1.SUPPLIER_NUMBER = SUPPLIERS1.SUPPLIER_NUMBER
WHERE SHIPMENTS1.PROJECT_NUMBER = 'J1';

--4
SELECT * FROM SHIPMENTS1 WHERE QUANTITY >=300 AND QUANTITY <=700;

--5
SELECT COLOR,CITY FROM PARTS1;

--6
SELECT DISTINCT
    S.SUPPLIER_NUMBER,
    PA.PART_NUMBER,
    PR.PROJECT_NUMBER
FROM
    SHIPMENTS1 SH
JOIN SUPPLIERS1 S ON S.SUPPLIER_NUMBER = SH.SUPPLIER_NUMBER
JOIN PARTS1 PA ON PA.PART_NUMBER = SH.PART_NUMBER
JOIN PROJECTS1 PR ON PR.PROJECT_NUMBER = SH.PROJECT_NUMBER
WHERE
    S.CITY = PA.CITY
    AND PA.CITY = PR.CITY
    AND S.CITY = PR.CITY;
    
    
SELECT sh.SUPPLIER_NUMBER, sh.PART_NUMBER, sh.PROJECT_NUMBER
FROM SHIPMENTS1 sh
JOIN SUPPLIERS1 s ON sh.SUPPLIER_NUMBER = s.SUPPLIER_NUMBER
JOIN PARTS1 p ON sh.PART_NUMBER = p.PART_NUMBER
JOIN PROJECTS1 pr ON sh.PROJECT_NUMBER = pr.PROJECT_NUMBER
WHERE s.CITY = p.CITY AND p.CITY = pr.CITY;


--7
SELECT SH.SUPPLIER_NUMBER,SH.PART_NUMBER,SH.PROJECT_NUMBER
FROM SHIPMENTS1 SH
JOIN SUPPLIERS1 S ON SH.SUPPLIER_NUMBER = S.SUPPLIER_NUMBER
JOIN PARTS1 P ON SH.PART_NUMBER = P.PART_NUMBER
JOIN PROJECTS1 PR ON SH.PROJECT_NUMBER = PR.PROJECT_NUMBER
WHERE S.CITY <> P.CITY AND P.CITY <> PR.CITY AND PR.CITY <> S.CITY

SELECT DISTINCT
    S.SUPPLIER_NUMBER,
    PA.PART_NUMBER,
    PR.PROJECT_NUMBER
FROM
    SHIPMENTS1 SH
JOIN SUPPLIERS1 S ON S.SUPPLIER_NUMBER = SH.SUPPLIER_NUMBER
JOIN PARTS1 PA ON PA.PART_NUMBER = SH.PART_NUMBER
JOIN PROJECTS1 PR ON PR.PROJECT_NUMBER = SH.PROJECT_NUMBER
WHERE
    S.CITY != PA.CITY
    AND PA.CITY != PR.CITY
    AND S.CITY != PR.CITY;
    
    
--9
SELECT DISTINCT
P.PART_NUMBER,
P.PROJECT_NAME,
P.COLOR,
P.WEIGHT,
P.CITY
FROM PARTS1 P
JOIN SHIPMENTS1 SH ON SH.PART_NUMBER = P.PART_NUMBER
JOIN SUPPLIERS1 S ON S.SUPPLIER_NUMBER = SH.SUPPLIER_NUMBER
WHERE S.CITY ='BOMBAY';

--10
SELECT DISTINCT
PA.PART_NUMBER FROM PARTS1 PA
JOIN SHIPMENTS1 SH ON SH.PART_NUMBER = PA.PART_NUMBER
JOIN SUPPLIERS1 S ON SH.SUPPLIER_NUMBER = S.SUPPLIER_NUMBER
JOIN PROJECTS1 PR ON SH.PROJECT_NUMBER = PR.PROJECT_NUMBER
WHERE
S.CITY='BOMBAY' AND
PR.CITY='BOMBAY';

--get all pairs of city names such that the supplier in the first city suppliers to a project in another city
SELECT DISTINCT S.SUPPLIER_NUMBER,PR.PROJECT_NUMBER
FROM SHIPMENTS1 SH
JOIN SUPPLIERS1 S ON SH.SUPPLIER_NUMBER = S.SUPPLIER_NUMBER
JOIN PROJECTS1 PR ON SH.PROJECT_NUMBER = PR.PROJECT_NUMBER
WHERE S.CITY <> PR.CITY;

SELECT DISTINCT
    S.CITY AS SUPPLIER_CITY,
    PR.CITY AS PROJECT_CITY
FROM
    SHIPMENTS1 SH
JOIN SUPPLIERS1 S ON SH.SUPPLIER_NUMBER = S.SUPPLIER_NUMBER
JOIN PROJECTS1 PR ON SH.PROJECT_NUMBER = PR.PROJECT_NUMBER
WHERE
    S.CITY <> PR.CITY;


--GET PROJECT NUMBERS FOR PROJECTS SUPPLIED BY AT LEAST ONE SUPPLIER WHO DOES NOT LIVE IN THE THE SAME CITY
SELECT DISTINCT PR.PROJECT_NUMBER
FROM SHIPMENTS1 SH
JOIN SUPPLIERS1 S ON SH.SUPPLIER_NUMBER = S.SUPPLIER_NUMBER
JOIN PROJECTS1 PR ON SH.PROJECT_NUMBER = PR.PROJECT_NUMBER
WHERE 
S.CITY <> PR.CITY

--GET ALL PAIRS FOR PART NUMBERS SUCH THE SOME SUPPLIER SUPPLIES BOTH THE INDICATED PARTS
SELECT DISTINCT SH1.PART_NUMBER AS PART1,
SH2.PART_NUMBER AS PART2
FROM SHIPMENTS SH1
JOIN SHIPMENTS SH2 ON SH1.SUPPLIER_NUMBER = SH2.SUPPLIER_NUMBER
WHERE SH1.PART_NUMBER <> SH2.PART_NUMBER; 

SELECT DISTINCT
    SH1.PART_NUMBER AS PART1,
    SH2.PART_NUMBER AS PART2
FROM
    SHIPMENTS1 SH1
JOIN SHIPMENTS1 SH2 ON SH1.SUPPLIER_NUMBER = SH2.SUPPLIER_NUMBER
WHERE
    SH1.PART_NUMBER <> SH2.PART_NUMBER;
    
    
--GET TOTAL NUMBER OF PROJECTS SUPPLIED BY SUPPLIER S1
SELECT COUNT(SH.PROJECT_NUMBER) AS TOTALPROJ
FROM SHIPMENTS1 SH
WHERE SH.SUPPLIER_NUMBER = 'S1';

--GET COLOR OF PARTS SUPPLIED BY S1
SELECT DISTINCT PA.COLOR 
FROM SHIPMENTS1 SH
JOIN PARTS1 PA ON SH.PART_NUMBER=PA.PART_NUMBER
WHERE SH.SUPPLIER_NUMBER = 'S1'; 

--GET TOTAL QUANTITY OF PART P1 SUPPLIED BY S1
SELECT SUM(SH.QUANTITY) AS TOTALQUANTITY
FROM SHIPMENTS1 SH
WHERE SH.PART_NUMBER ='P1' AND
SH.SUPPLIER_NUMBER= 'S1';

--FOR EACH PART BEING SUPPLIED TO A PROJECT,GET THE PART NUMBER,PROJECT NUMBER AND THE CORRESPONDING TOTAL QUANTITY
SELECT PART_NUMBER,
PROJECT_NUMBER,
SUM(QUANTITY) AS TOTALQUANTITY
FROM SHIPMENTS1
GROUP BY PART_NUMBER,PROJECT_NUMBER;


--ASS3 1 GET PART NUMBER 0F PARTS SUPPLIED TO SOME PROJECT IN AN AERAGE QUANTITY OF MORE THAN 350
SELECT PART_NUMBER 
FROM (
    SELECT PART_NUMBER,
           AVG(QUANTITY) AS AVG_QUANTITY
    FROM SHIPMENTS1
    GROUP BY PART_NUMBER
) AS PARTAVERAGE
WHERE AVG_QUANTITY > 350;

--GET PART NUMBERS FOR PARTS SUPPLIED TO ANY PROJECT IN BOMBAY
SELECT DISTINCT SH.PART_NUMBER 
FROM SHIPMENTS1 SH
WHERE SH.PROJECT_NUMBER IN(
SELECT PR.PROJECT_NUMBER
FROM PROJECTS1 PR
WHERE PR.CITY ='BOMBAY'
);

--GET SUPPLIER NUMBERS FOR SUPPLIERS SUPPLYING AT LEAST ONE PART SUPPLIED BY AT LEAST ONE SUPPLIER WHO SUPPLIERS AT LEAST ONE RED PART
SELECT DISTINCT S1.SUPPLIER_NUMBER
FROM SHIPMENTS1 S1
WHERE S1.PART_NUMBER IN (
SELECT DISTINCT S2.PART_NUMBER 
FROM SHIPMENTS1 S2 
WHERE S2.SUPPLIER_NUMBER IN (
SELECT S3.SUPPLIER_NUMBER 
FROM SHIPMENTS1 S3
JOIN PARTS1 P ON P.PARTS_NUMBER=S3.SUPPLIER_NUMBER
WHERE P.COLOR='RED')
)
);

SELECT DISTINCT S1.SUPPLIER_NUMBER
FROM SHIPMENTS1 S1
WHERE S1.PART_NUMBER IN (
    SELECT DISTINCT S2.PART_NUMBER
    FROM SHIPMENTS1 S2
    WHERE S2.SUPPLIER_NUMBER IN (
        SELECT DISTINCT S3.SUPPLIER_NUMBER
        FROM SHIPMENTS1 S3
        JOIN PARTS1 P ON S3.PART_NUMBER = P.PART_NUMBER
        WHERE P.COLOR = 'RED'
    )
);

--GET SUPPLIER NUMBERS FOR SUPPLIERS WITH A STATUS LOWER THAN THAT OF SUPPLIER S1
SELECT SUPPLIER_NUMBER 
FROM SUPPLIERS1
WHERE STATUS < (
SELECT STATUS 
FROM SUPPLIERS1 
WHERE SUPPLIER_NUMBER='S1'
);
--GET THE PROJECT NUMBERS FOR PROJECTS SUPPLIED WITH PART P1 IN AN AVERAGE QUANTITY GREATER THAN THE GREATEST QUANTITY IN WHICH ANY PART IS SUPPLIED TO PROJECT J1
SELECT PROJECT_NUMBER
FROM (
    SELECT PROJECT_NUMBER, AVG(QUANTITY) AS AVG_QUANTITY
    FROM SHIPMENTS1
    WHERE PART_NUMBER = 'P1'
    GROUP BY PROJECT_NUMBER
) AS AvgQuantities
WHERE AVG_QUANTITY > (
    SELECT MAX(QUANTITY)
    FROM SHIPMENTS1
    WHERE PROJECT_NUMBER = 'J1'
);

--GET SUPPLIER NUMBERS FOR SUPPLIERS SUPPLYING TO SOME PROJECT WITH PART P1 IN A QUANTITY LESS THAN THE AVERAGE SHIPMENT QUANTITY OF PART P1 FOR THAT PROJECT



